#Default port is 8761
server:
  port: 8761
#server:
#  port: 8888
  ssl:
     key-store: proarchskeystore.p12
     key-store-password: proarchs
     keyStoreType: PKCS12
     keyAlias: proarchs

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: https://localhost:8761  

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.toystore.ecomm.eureka: DEBUG
