#Default port is 8761
server:
  port: 8761
#server:
#  port: 8888
  ssl:
     key-store: proarchskeystore.p12
     key-store-password: proarchs
     keyStoreType: PKCS12
     keyAlias: proarchs

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.toystore.ecomm.eureka: DEBUG
